from __future__ import annotations

from ozz8bit.isa import INSTRUCTION_SET


FETCH_SEQUENCE = [
    "PC -> MAR",
    "MEM[MAR] -> IR, PC <- PC + 1",
]

MICROCODE_TABLES: dict[int, list[str]] = {
    0x00: [*FETCH_SEQUENCE, "IDLE"],
    0x01: [*FETCH_SEQUENCE, "HALT"],
    0x02: [*FETCH_SEQUENCE, "READ IMM8", "PUSH PC", "PUSH FLAGS", "VECTOR <- IMM8", "PC <- IVT[VECTOR]"],
    0x03: [*FETCH_SEQUENCE, "POP FLAGS", "POP PC"],
    0x10: [*FETCH_SEQUENCE, "READ REG IDS", "SRC -> DST"],
    0x11: [*FETCH_SEQUENCE, "READ REG ID", "READ IMM8", "IMM8 -> DST"],
    0x12: [*FETCH_SEQUENCE, "READ REG ID", "READ IMM16", "IMM16 -> DST"],
    0x13: [*FETCH_SEQUENCE, "READ REG ID", "READ ADDR16", "MEM[ADDR] -> DST"],
    0x14: [*FETCH_SEQUENCE, "READ ADDR16", "READ REG ID", "SRC -> MEM[ADDR]"],
    0x15: [*FETCH_SEQUENCE, "READ REG ID", "READ BASE REG", "READ DISP8", "MEM[BASE+DISP] -> DST"],
    0x16: [*FETCH_SEQUENCE, "READ BASE REG", "READ DISP8", "READ REG ID", "SRC -> MEM[BASE+DISP]"],
    0x17: [*FETCH_SEQUENCE, "READ REG ID", "PUSH SRC"],
    0x18: [*FETCH_SEQUENCE, "READ REG ID", "POP DST"],
    0x20: [*FETCH_SEQUENCE, "READ REG IDS", "ALU ADD", "WRITE DST", "UPDATE FLAGS"],
    0x21: [*FETCH_SEQUENCE, "READ REG ID", "READ IMM8", "ALU ADD", "WRITE DST", "UPDATE FLAGS"],
    0x22: [*FETCH_SEQUENCE, "READ REG IDS", "ALU SUB", "WRITE DST", "UPDATE FLAGS"],
    0x23: [*FETCH_SEQUENCE, "READ REG ID", "READ IMM8", "ALU SUB", "WRITE DST", "UPDATE FLAGS"],
    0x24: [*FETCH_SEQUENCE, "READ REG IDS", "ALU MUL", "WRITE DST", "UPDATE FLAGS"],
    0x25: [*FETCH_SEQUENCE, "READ REG ID", "READ IMM8", "ALU MUL", "WRITE DST", "UPDATE FLAGS"],
    0x26: [*FETCH_SEQUENCE, "READ REG IDS", "ALU DIV", "WRITE DST", "UPDATE FLAGS"],
    0x27: [*FETCH_SEQUENCE, "READ REG ID", "READ IMM8", "ALU DIV", "WRITE DST", "UPDATE FLAGS"],
    0x28: [*FETCH_SEQUENCE, "READ REG IDS", "ALU MOD", "WRITE DST", "UPDATE FLAGS"],
    0x29: [*FETCH_SEQUENCE, "READ REG ID", "READ IMM8", "ALU MOD", "WRITE DST", "UPDATE FLAGS"],
    0x2A: [*FETCH_SEQUENCE, "READ REG IDS", "ALU AND", "WRITE DST", "UPDATE FLAGS"],
    0x2B: [*FETCH_SEQUENCE, "READ REG ID", "READ IMM8", "ALU AND", "WRITE DST", "UPDATE FLAGS"],
    0x2C: [*FETCH_SEQUENCE, "READ REG IDS", "ALU OR", "WRITE DST", "UPDATE FLAGS"],
    0x2D: [*FETCH_SEQUENCE, "READ REG ID", "READ IMM8", "ALU OR", "WRITE DST", "UPDATE FLAGS"],
    0x2E: [*FETCH_SEQUENCE, "READ REG IDS", "ALU XOR", "WRITE DST", "UPDATE FLAGS"],
    0x2F: [*FETCH_SEQUENCE, "READ REG ID", "READ IMM8", "ALU XOR", "WRITE DST", "UPDATE FLAGS"],
    0x30: [*FETCH_SEQUENCE, "READ REG IDS", "ALU CMP", "UPDATE FLAGS"],
    0x31: [*FETCH_SEQUENCE, "READ REG ID", "READ IMM8", "ALU CMP", "UPDATE FLAGS"],
    0x32: [*FETCH_SEQUENCE, "READ REG ID", "ALU INC", "WRITE DST", "UPDATE FLAGS"],
    0x33: [*FETCH_SEQUENCE, "READ REG ID", "ALU DEC", "WRITE DST", "UPDATE FLAGS"],
    0x34: [*FETCH_SEQUENCE, "READ REG ID", "ALU NEG", "WRITE DST", "UPDATE FLAGS"],
    0x35: [*FETCH_SEQUENCE, "READ REG ID", "ALU ABS", "WRITE DST", "UPDATE FLAGS"],
    0x36: [*FETCH_SEQUENCE, "READ REG ID", "ALU NOT", "WRITE DST", "UPDATE FLAGS"],
    0x37: [*FETCH_SEQUENCE, "READ REG ID", "ALU SHL", "WRITE DST", "UPDATE FLAGS"],
    0x38: [*FETCH_SEQUENCE, "READ REG ID", "ALU SHR", "WRITE DST", "UPDATE FLAGS"],
    0x39: [*FETCH_SEQUENCE, "READ REG ID", "ALU ROL", "WRITE DST", "UPDATE FLAGS"],
    0x3A: [*FETCH_SEQUENCE, "READ REG ID", "ALU ROR", "WRITE DST", "UPDATE FLAGS"],
    0x40: [*FETCH_SEQUENCE, "READ ADDR16", "PC <- ADDR"],
    0x41: [*FETCH_SEQUENCE, "READ ADDR16", "IF ZF THEN PC <- ADDR"],
    0x42: [*FETCH_SEQUENCE, "READ ADDR16", "IF !ZF THEN PC <- ADDR"],
    0x43: [*FETCH_SEQUENCE, "READ ADDR16", "IF !ZF AND NF == OF THEN PC <- ADDR"],
    0x44: [*FETCH_SEQUENCE, "READ ADDR16", "IF NF != OF THEN PC <- ADDR"],
    0x45: [*FETCH_SEQUENCE, "READ ADDR16", "IF NF == OF THEN PC <- ADDR"],
    0x46: [*FETCH_SEQUENCE, "READ ADDR16", "IF ZF OR NF != OF THEN PC <- ADDR"],
    0x47: [*FETCH_SEQUENCE, "READ ADDR16", "PUSH PC", "PC <- ADDR"],
    0x48: [*FETCH_SEQUENCE, "POP PC"],
}


def validate_tables() -> list[str]:
    errors: list[str] = []
    for opcode, spec in INSTRUCTION_SET.items():
        if opcode not in MICROCODE_TABLES:
            errors.append(f"Missing microcode for opcode 0x{opcode:02X} ({spec.mnemonic})")
    return errors
